### ISSUE TITLE
Hanging on Creating Domain

### ISSUE THREAD

**Issue by felixxcheng** [bryansteiner/gpu-passthrough-tutorial#12]
I have a thinkpad x1 extreme gen 2, I am following your guide exactly except for passing the NVMe SSD.   I also modified the bind and unbind script as well as kvm.conf to ommit the NVMe, and also the GPU serial/USB as there isn't any on a laptop's dGPU.

When I begin the installation of the VM it hangs on Creating Domain.

I end up having to xkill virt manager and when I check sudo service libvirt status, the last log has something to do with the GPU.

Any ideas how I can further diagnose this problem?  

I have a few guesses.   

1. maybe it has somethig to do with UEFI, as if I just create a VM with BIOS, there are no issues, but unfortunately no passthrough

2. Hook Helper tool is somehow failing to to bind the GPU

3.  Maybe it has something to do with my not having multiple monitors as this is a laptop

thank you for your help

**Comment by bryansteiner** [comment]
My first guess would be that it's hanging because virt-manager is trying to run the hook-scripts but you haven't made them and their directories executable:
`chmod +x <hook-scripts>`

**Comment by chironjit** [comment]
If your issue is related to the graphics card, its likely that virtman can't unbind the dgpu as its still being used by the display manager. If you have an NVidia dgpu you can confirm this by checking the running processes on your card using nvidia-smi.

If you do have a display service running on your dgpu, AND you are using Pop OS, you can try turning your dGPU to hybrid or compute-only by typing `sudo system76-power graphics hybrid` or `sudo system76-power graphics compute` and then restarting your display manager (or just restarting your laptop). More guide on [Pop OS graphics switching](https://support.system76.com/articles/graphics-switch-pop/).
